[package]
name = "airpodsd"
version = "0.1.0"
edition = "2021"

[dependencies]
bluer = { version = "0.17.3", features = ["l2cap", "bluetoothd"] }
futures-util = "0.3.30"
ksni = "0.2.2"
mpris = "2.0.1"
tokio = { version = "1", features = ["full"] }
